title: "Ranjana Rajendran"
description: "ML Engineer • Distributed Systems • Agentic AI"
repository: "ranjanarajendran/ranjanarajendran.github.io"
url: "https://ranjanarajendran.github.io"
baseurl: ""

remote_theme: "academicpages/academicpages"

markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /projects/:path/
  publications:
    output: true
    permalink: /publications/:path/

author:
  name: "Ranjana Rajendran"
  avatar: "assets/img/avatar.png"
  bio: "ML/AI Engineer with 10+ years in big data & distributed systems. Exploring agentic AI, RAG, and scalable ML pipelines."
  location: "Seattle, WA"
  email: "ranjana.rajendran@gmail.com"
  github: "ranjanarajendran"
  linkedin: "ranjana-rajendran"

include: ["_pages"]
